=== mamift/LinqToXsdCore/LinqToXsd.Schemas/UK CabinetOffice/eDeliver-eis/LHA_rates.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio 6.1.17.0 (http://www.liquid-technologies.com)-->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Andrew Harding (The Rent Service) -->
<xsd:schema xmlns:rep="http://www.therentservice.gov.uk/schema/LHA_rates.xsd" xmlns:cmn="http://www.therentservice.gov.uk/schema/Common_ed.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.therentservice.gov.uk/schema/LHA_rates.xsd" version="edeliver_v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import schemaLocation="Common_ed.xsd" namespace="http://www.therentservice.gov.uk/schema/Common_ed.xsd" />
  <xsd:annotation>
    <xsd:appinfo xmlns:gms="http://www.govtalk.gov.uk/CM/gms">
			<Metadata xmlns="http://www.govtalk.gov.uk/CM/gms-xs">
				<Creator>The Rent Service (helpdesk@therentservice.gov.uk)</Creator>
				<Date>
					<Created>2007-07-04</Created>
				</Date>
				<Description>Schema for distributing LHA rates</Description>
				<Identifier>LHA_rates.xsd-edeliver_v1-1</Identifier>
				<Language>[ISO 639-2/B] ENG</Language>
				<Publisher>The Rent Service, 5 Welbeck Street, London, W1G 9YQ</Publisher>
				<Subject>
					<Category>People, communities and living</Category>
					<Keyword>Housing Benefit</Keyword>
					<Keyword>Rent Service</Keyword>
					<Keyword>Local Housing Allowance</Keyword>
				</Subject>
				<Title>Local Housing Allowance Rates</Title>
			</Metadata>
		</xsd:appinfo>
  </xsd:annotation>
  <xsd:element name="LHARATES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Manifest" type="cmn:Manifest">
          <xsd:annotation>
            <xsd:documentation>Manifest Details</xsd:documentation>
          </xsd:annotation>
        </xsd:element>
        <xsd:sequence maxOccurs="unbounded">
          <xsd:element name="BRMA_ID">
            <xsd:simpleType>
              <xsd:restriction base="xsd:int" />
            </xsd:simpleType>
          </xsd:element>
          <xsd:element name="BRMA_name" type="cmn:AddressLineType" />
          <xsd:element name="Cat_A_W">
            <xsd:annotation>
              <xsd:documentation>Room with shared facs</xsd:documentation>
            </xsd:annotation>
            <xsd:simpleType>
              <xsd:restriction base="xsd:decimal" />
            </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Cat_B_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>1 Bedroom</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_C_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>2 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_D_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>3 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_E_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>4 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_F_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>5 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element minOccurs="0" name="Cat_G_W" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>NonStatutory - 6 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_A_M">
            <xsd:annotation>
              <xsd:documentation>Room with shared facs</xsd:documentation>
            </xsd:annotation>
            <xsd:simpleType>
              <xsd:restriction base="xsd:decimal" />
            </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Cat_B_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>1 Bedroom</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_C_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>2 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_D_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>3 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_E_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>4 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="Cat_F_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>5 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element minOccurs="0" name="Cat_G_M" type="xsd:decimal">
            <xsd:annotation>
              <xsd:documentation>NonStatutory - 6 Bedrooms</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
          <xsd:element name="ValidFrom" type="cmn:DateType" />
          <xsd:element name="ValidTo" type="cmn:DateType" />
        </xsd:sequence>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mamift/LinqToXsdCore/GeneratedSchemaLibraries/UK CabinetOffice/eDeliver-eis/SampleFile_LHA.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 6.1.17.0 (http://www.liquid-technologies.com) -->
<tnsa:LHARATES xmlns:tns="http://www.therentservice.gov.uk/schema/Common_ed.xsd" xmlns:tnsa="http://www.therentservice.gov.uk/schema/LHA_rates.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.therentservice.gov.uk/schema/LHA_rates.xsd C:\ElectronicInterface\EDeliver\v1.1\LHA_rates.xsd">
  <tnsa:Manifest>
    <tns:SenderRecipient>
      <tns:LACode>string</tns:LACode>
      <tns:OfficeCode>30</tns:OfficeCode>
    </tns:SenderRecipient>
    <tns:Timestamp>
      <tns:CompilationDate>1989-02-13</tns:CompilationDate>
      <tns:CompilationTime>22:16:29.44</tns:CompilationTime>
    </tns:Timestamp>
  </tnsa:Manifest>
  <tnsa:BRMA_ID>3101</tnsa:BRMA_ID>
  <tnsa:BRMA_name>string</tnsa:BRMA_name>
  <tnsa:Cat_A_W>4372.574905803945093</tnsa:Cat_A_W>
  <tnsa:Cat_B_W>-7663.385094196054907</tnsa:Cat_B_W>
  <tnsa:Cat_C_W>4352.194905803945093</tnsa:Cat_C_W>
  <tnsa:Cat_D_W>-8036.665094196054907</tnsa:Cat_D_W>
  <tnsa:Cat_E_W>-1451.385094196054907</tnsa:Cat_E_W>
  <tnsa:Cat_F_W>-4050.185094196054907</tnsa:Cat_F_W>
  <tnsa:Cat_G_W>-3350.605094196054907</tnsa:Cat_G_W>
  <tnsa:Cat_A_M>6429.974905803945093</tnsa:Cat_A_M>
  <tnsa:Cat_B_M>1105.274905803945093</tnsa:Cat_B_M>
  <tnsa:Cat_C_M>-9819.745094196054907</tnsa:Cat_C_M>
  <tnsa:Cat_D_M>-6949.605094196054907</tnsa:Cat_D_M>
  <tnsa:Cat_E_M>-1127.025094196054907</tnsa:Cat_E_M>
  <tnsa:Cat_F_M>-9519.425094196054907</tnsa:Cat_F_M>
  <tnsa:Cat_G_M>-4755.525094196054907</tnsa:Cat_G_M>
  <tnsa:ValidFrom>1973-11-07</tnsa:ValidFrom>
  <tnsa:ValidTo>2016-08-01</tnsa:ValidTo>
  <tnsa:BRMA_ID>-5784</tnsa:BRMA_ID>
  <tnsa:BRMA_name>string</tnsa:BRMA_name>
  <tnsa:Cat_A_W>-5736.405094196054907</tnsa:Cat_A_W>
  <tnsa:Cat_B_W>-8335.825094196054907</tnsa:Cat_B_W>
  <tnsa:Cat_C_W>82.054905803945093</tnsa:Cat_C_W>
  <tnsa:Cat_D_W>5749.394905803945093</tnsa:Cat_D_W>
  <tnsa:Cat_E_W>-6004.225094196054907</tnsa:Cat_E_W>
  <tnsa:Cat_F_W>-3921.585094196054907</tnsa:Cat_F_W>
  <tnsa:Cat_G_W>3920.074905803945093</tnsa:Cat_G_W>
  <tnsa:Cat_A_M>-4963.085094196054907</tnsa:Cat_A_M>
  <tnsa:Cat_B_M>6986.874905803945093</tnsa:Cat_B_M>
  <tnsa:Cat_C_M>4872.334905803945093</tnsa:Cat_C_M>
  <tnsa:Cat_D_M>-2621.865094196054907</tnsa:Cat_D_M>
  <tnsa:Cat_E_M>8090.034905803945093</tnsa:Cat_E_M>
  <tnsa:Cat_F_M>-1678.405094196054907</tnsa:Cat_F_M>
  <tnsa:Cat_G_M>6578.074905803945093</tnsa:Cat_G_M>
  <tnsa:ValidFrom>2002-02-01</tnsa:ValidFrom>
  <tnsa:ValidTo>2007-07-13</tnsa:ValidTo>
  <tnsa:BRMA_ID>2487</tnsa:BRMA_ID>
  <tnsa:BRMA_name>string</tnsa:BRMA_name>
  <tnsa:Cat_A_W>9137.374905803945093</tnsa:Cat_A_W>
  <tnsa:Cat_B_W>-5490.765094196054907</tnsa:Cat_B_W>
  <tnsa:Cat_C_W>-3418.245094196054907</tnsa:Cat_C_W>
  <tnsa:Cat_D_W>-7677.185094196054907</tnsa:Cat_D_W>
  <tnsa:Cat_E_W>7555.114905803945093</tnsa:Cat_E_W>
  <tnsa:Cat_F_W>-1781.585094196054907</tnsa:Cat_F_W>
  <tnsa:Cat_G_W>-3270.205094196054907</tnsa:Cat_G_W>
  <tnsa:Cat_A_M>-3625.125094196054907</tnsa:Cat_A_M>
  <tnsa:Cat_B_M>6226.334905803945093</tnsa:Cat_B_M>
  <tnsa:Cat_C_M>-7755.325094196054907</tnsa:Cat_C_M>
  <tnsa:Cat_D_M>2894.274905803945093</tnsa:Cat_D_M>
  <tnsa:Cat_E_M>-3580.085094196054907</tnsa:Cat_E_M>
  <tnsa:Cat_F_M>3821.974905803945093</tnsa:Cat_F_M>
  <tnsa:Cat_G_M>-2579.545094196054907</tnsa:Cat_G_M>
  <tnsa:ValidFrom>1978-11-04</tnsa:ValidFrom>
  <tnsa:ValidTo>1997-03-16</tnsa:ValidTo>
</tnsa:LHARATES>
